### ISSUE TITLE
travis: flake8 not running

### ISSUE THREAD

**Issue by jcarrano** [RIOT-OS/RIOT#12058]
#### Description

Flake8 is not running on travis-CI. This may be an issue with the docker image.

#### Steps to reproduce the issue

Look at the output of the CI run:

```
Running './dist/tools/flake8/check.sh' x

Command output:

	./dist/tools/flake8/check.sh: cannot execute "python3 -m flake8"!
```

Trying to run flake8 directly in the docker image it get:

```
$ sudo docker run riot/riotbuild python3 -m flake8
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/flake8/__main__.py", line 2, in <module>
    from flake8.main import cli
  File "/usr/local/lib/python3.6/dist-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/usr/local/lib/python3.6/dist-packages/flake8/main/application.py", line 14, in <module>
    from flake8.main import options
  File "/usr/local/lib/python3.6/dist-packages/flake8/main/options.py", line 3, in <module>
    from flake8.main import debug
  File "/usr/local/lib/python3.6/dist-packages/flake8/main/debug.py", line 7, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by aabadie** [comment]
It is strange but looking at riotdocker history, it seems the regression was introduced by https://github.com/RIOT-OS/riotdocker/pull/56: there's a line in the Dockerfile that uninstall some requirements and setuptools is one of the two.
Was Murdock running the latest riotbuild image ?
