### ISSUE TITLE
Tabs和Cell设置为Navigate后，返回报错

### ISSUE THREAD

**Issue by wzhq0598** [RIOT-OS/RIOT#12820]
thirdScriptError
Cannot read property 'getComputedName' of undefined;at api nextTick callback function
TypeError: Cannot read property 'getComputedName' of undefined
    at ye.trigger (http://127.0.0.1:18760/appservice/vant/tabs/index.js:147:29)
    at Function.<anonymous> (http://127.0.0.1:18760/appservice/vant/tabs/index.js:200:24)
    at WAService.js:1:102871
    at Function.bd (WAService.js:1:776743)
    at WAService.js:1:102871
    at WAService.js:1:90451

**Comment by miri64** [comment]
I think this was opened by mistake...
