### ISSUE TITLE
gcoap example crashes on LLVM

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#17591]
#### Description

The gcoap example, run on microbit-v2, currently crashes right after startup when using LLVM.

#### Steps to reproduce the issue

On current master:

```
$ make -C examples/gcoap BOARD=microbit-v2 all flash term TOOLCHAIN=llvm BUILD_IN_DOCKER=1
[...]
[press reset because terminal doesn't start fast enough to catch error]
```

(BUILD_IN_DOCKER for better reproducibility; effect is the same on my local system).

#### Expected results

Get a shell. (As happens when not overriding the toolchain).

#### Actual results

```
2022-01-30 15:02:37,698 # NETOPT_RX_END_IRQ not implemented by driver
2022-01-30 15:02:37,702 # NETOPT_TX_END_IRQ not implemented by driver
2022-01-30 15:02:37,706 # main(): This is RIOT! (Version:0xb579
2022-01-30 15:02:37,708 # *** RIOT kernel panic:
2022-01-30 15:02:37,709 # FAILED ASSERTION.
2022-01-30 15:02:37,710 # 
2022-01-30 15:02:37,718 #       pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2022-01-30 15:02:37,727 #         - | isr_stack            | -        - |   - |    512 (  224) (  288) | 0x20000000 | 0x200001c8
2022-01-30 15:02:37,736 #         1 | main                 | pending  Q |   7 |   1536 (  496) ( 1040) | 0x200005cc | 0x200009dc 
2022-01-30 15:02:37,744 #         2 | 6lo                  | bl rx    _ |   3 |   1024 (  368) (  656) | 0x20003698 | 0x2000398c 
2022-01-30 15:02:37,753 #         3 | ipv6                 | bl rx    _ |   4 |   1024 (  368) (  656) | 0x20001274 | 0x2000153c 
2022-01-30 15:02:37,762 #         4 | udp                  | bl rx    _ |   5 |   1024 (  264) (  760) | 0x20003e7c | 0x20004174 
2022-01-30 15:02:37,770 #         5 | coap                 | bl anyfl _ |   6 |   1108 (  220) (  888) | 0x20000ccc | 0x20001044 
2022-01-30 15:02:37,779 #         6 | nrf802154            | running  Q |   2 |   1024 (  716) (  308) | 0x200019f8 | 0x20001ca4 
2022-01-30 15:02:37,786 #           | SUM                  |            |     |   7252 ( 2656) ( 4596)
2022-01-30 15:02:37,787 # 
2022-01-30 15:02:37,787 # *** halted.
```

#### Versions

Current master is 4aa173d3

OS and build versions shouldn't matter, for it's all built in docker (but behaves the same on Debian GNU/Linux with GCC with clang 13.0.1-+rc3-1~exp1)

**Comment by chrysn** [comment]
I'm working to debug it; backtrace of the crash:

```
Breakpoint 2, print_ipsr () at panic.c:29
29      in panic.c
(gdb) bt
#0  print_ipsr () at panic.c:29
#1  panic_arch () at panic.c:41
#2  0x0000117a in core_panic (crash_code=<optimized out>, message=<optimized out>) at panic.c:91
#3  0x0000b578 in ieee802154_submac_process_ev (submac=0x13ee4 <assert_crash_message>, ev=<optimized out>)
    at submac.c:285
#4  0x0000ce5a in ieee802154_submac_tx_done_cb (submac=0x200018c0 <nrf802154_netdev+40>)
    at /data/riotbuild/riotbase/sys/include/net/ieee802154/submac.h:595
#5  _isr (netdev=0x20001898 <nrf802154_netdev>) at netdev_ieee802154_submac.c:200
#6  0x0000671e in _gnrc_netif_thread (args=<optimized out>) at gnrc_netif.c:1890
#7  0x0000139a in sched_switch (other_prio=<optimized out>) at sched.c:300
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
