### ISSUE TITLE
micropython: Example test fails

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#18487]
#### Description

The test shipped with examples/micropython crashes on native. I vaguely doubt that what is tested here would have good changes to not be UB at some point, but I don't know the micropython port well enough to have more than a hunch that what happens with xtimer in this test would be extremely hard to implement.

#### Steps to reproduce the issue

* On native, `make -C examples/micropython all test`

#### Expected results

It passes

#### Actual results

```
>>> t = xtimer.xtimer(inc_a)
t = xtimer.xtimer(inc_a)
>>> utime.time()
utime.time()
4920
>>> t.set(500000)
t.set(500000)
>>> while a==0: pass
while a==0: pass
... 

>>> utime.time()
utime.time()
make[1]: *** [/home/chrysn/git/RIOT/Makefile.include:869: cleanterm] Floating point exception

Traceback (most recent call last):
  File "/home/chrysn/git/RIOT/examples/micropython/tests/01-run.py", line 84, in <module>
    sys.exit(run(testfunc))
  File "/home/chrysn/git/RIOT/dist/pythonlibs/testrunner/__init__.py", line 30, in run
    testfunc(child)
  File "/home/chrysn/git/RIOT/examples/micropython/tests/01-run.py", line 77, in testfunc
    duration = get_time() - before
  File "/home/chrysn/git/RIOT/examples/micropython/tests/01-run.py", line 11, in get_time
    res = int(child.readline().rstrip())
ValueError: invalid literal for int() with base 10: 'make[1]: *** [/home/chrysn/git/RIOT/Makefile.include:869: cleanterm] Floating point exception'
make: *** [/home/chrysn/git/RIOT/makefiles/tests/tests.inc.mk:22: test] Error 1
make: Leaving directory '/home/chrysn/git/RIOT/examples/micropython'
```

#### Versions

current master and 2022.07-RC3

**Comment by kaspar030** [comment]
duplicate: https://github.com/RIOT-OS/RIOT/issues/15870
