### ISSUE TITLE
b-l072z-lrwan1: tests/ztimer_overhead: test failure

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#19224]
#### Description

Found during [2023.01 release testing](https://github.com/RIOT-OS/RIOT/actions/runs/4039331869/jobs/6943959150):

<details>

```
WARNING:b-l072z-lrwan1.tests/ztimer_overhead:make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/ztimer_overhead test
r
ssh -t rici@saclay.iot-lab.info 'socat - tcp:st-lrwan1-10.saclay.iot-lab.info:20000' 
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: buildtest)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 21
    ZTIMER_USEC->adjust_sleep = 25
ZTIMER_USEC auto_adjust params cleared
zitmer_overhead_set...
min=20 max=21 avg_diff=20
zitmer_overhead_sleep...
min=27 max=27 avg_diff=27
ZTIMER_USEC adjust params for b-l072z-lrwan1:
    CONFIG_ZTIMER_USEC_ADJUST_SET    20
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  27

Traceback (most recent call last):
  File "/home/runner/work/RIOT/RIOT/tests/ztimer_overhead/tests/01-run.py", line 33, in <module>
    sys.exit(run(testfunc))
  File "/home/runner/work/RIOT/RIOT/dist/pythonlibs/testrunner/__init__.py", line 30, in run
    testfunc(child)
  File "/home/runner/work/RIOT/RIOT/tests/ztimer_overhead/tests/01-run.py", line 29, in testfunc
    assert auto_adjust_sleep >= adjust_sleep - ADJUST_SLEEP_MARGIN
AssertionError
make: *** [/home/runner/work/RIOT/RIOT/makefiles/tests/tests.inc.mk:26: test] Error 1

Return value: 2
```
</details>

**Comment by crasbe** [comment]
Can't reproduce:

```
cbuec@W11nMate:~/RIOTstuff/riot-upstream/RIOT$ BOARD=b-l072z-lrwan1 make -C tests/sys/ztimer_overhead flash test -j
make: Entering directory '/home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead'
Building application "tests_ztimer_overhead" for "b-l072z-lrwan1" with CPU "stm32".

Cloning into '/home/cbuec/RIOTstuff/riot-upstream/RIOT/build/stm32/cmsis/l0'...
done.
HEAD is now at 69cd599 Release v1.9.3
Cloning into '/home/cbuec/RIOTstuff/riot-upstream/RIOT/build/pkg/cmsis'...
done.
HEAD is now at 2b7495b85 Merge branch 'develop'
Cloning into '/home/cbuec/RIOTstuff/riot-upstream/RIOT/build/pkg/mpaland-printf'...
done.
HEAD is now at 0dd4b64 test(test_suite): added support for PRINTF_DISABLE_SUPPORT_EXPONENTIAL
"make" -C /home/cbuec/RIOTstuff/riot-upstream/RIOT/pkg/cmsis/
...
"make" -C /home/cbuec/RIOTstuff/riot-upstream/RIOT/sys/ztimer
   text    data     bss     dec     hex filename
  11624     176    2372   14172    375c /home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead/bin/b-l072z-lrwan1/tests_ztimer_overhead.elf
/home/cbuec/RIOTstuff/riot-upstream/RIOT/dist/tools/openocd/openocd.sh flash /home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead/bin/b-l072z-lrwan1/tests_ztimer_overhead.elf
### Flashing Target ###
Open On-Chip Debugger 0.12.0+dev-00645-g49ef1d010 (2026-05-28-14:54) [https://github.com/STMicroelectronics/OpenOCD]
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
srst_only separate srst_nogate srst_open_drain connect_assert_srst
Info : clock speed 300 kHz
Info : STLINK V2J28M18 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.247895
Info : [stm32l0.cpu] Cortex-M0+ r0p1 processor detected
Info : [stm32l0.cpu] target has 4 breakpoints, 2 watchpoints
Info : [stm32l0.cpu] Examination succeed
Info : starting gdb server for stm32l0.cpu on 0
Info : Listening on port 44655 for gdb connections
    TargetName         Type       Endian TapName            State
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32l0.cpu        hla_target little stm32l0.cpu        unknown
Info : Unable to match requested speed 300 kHz, using 240 kHz
Info : Unable to match requested speed 300 kHz, using 240 kHz
[stm32l0.cpu] halted due to debug-request, current mode: Thread
xPSR: 0xf1000000 pc: 0x08000bd0 msp: 0x20000200
Info : Device: STM32L0xx (Cat.5)
Info : STM32L flash has dual banks. Bank (0) size is 96kb, base address is 0x8000000
auto erase enabled
wrote 12288 bytes from file /home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead/bin/b-l072z-lrwan1/tests_ztimer_overhead.elf in 3.799402s (3.158 KiB/s)
verified 11800 bytes in 0.626176s (18.403 KiB/s)
Info : Unable to match requested speed 300 kHz, using 240 kHz
Info : Unable to match requested speed 300 kHz, using 240 kHz
shutdown command invoked
Done flashing
r
/home/cbuec/RIOTstuff/riot-upstream/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2026-08-06_16.55.28-tests_ztimer_overhead-b-l072z-lrwan1" --no-reconnect --noprefix --no-repeat-command-on-empty-line
Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
�ress s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
...
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2026.10-devel-278-g307c08d)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 20
    ZTIMER_USEC->adjust_sleep = 29
ZTIMER_USEC auto_adjust params cleared
ztimer_overhead_set...
min=20 max=21 avg_diff=20
ztimer_overhead_sleep...
min=29 max=29 avg_diff=29
ZTIMER_USEC adjust params for b-l072z-lrwan1:
    CONFIG_ZTIMER_USEC_ADJUST_SET    20
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  29

make: Leaving directory '/home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead'
```

**Comment by crasbe** [comment]
I tested some more boards to rule out variation:

<img width="1700" height="956" alt="Image" src="https://github.com/user-attachments/assets/d6227966-354c-47ec-8c6d-f759480089d6" />

### Board 2
```
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2026.10-devel-278-g307c08d)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 20
    ZTIMER_USEC->adjust_sleep = 29
ZTIMER_USEC auto_adjust params cleared
ztimer_overhead_set...
min=20 max=21 avg_diff=20
ztimer_overhead_sleep...
min=29 max=29 avg_diff=29
ZTIMER_USEC adjust params for b-l072z-lrwan1:
    CONFIG_ZTIMER_USEC_ADJUST_SET    20
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  29

make: Leaving directory '/home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead'
cbuec@W11nMate:~/RIOTstuff/riot-upstream/RIOT$
```

### Board 3
```
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2026.10-devel-278-g307c08d)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 20
    ZTIMER_USEC->adjust_sleep = 29
ZTIMER_USEC auto_adjust params cleared
ztimer_overhead_set...
min=20 max=20 avg_diff=20
ztimer_overhead_sleep...
min=29 max=29 avg_diff=29
ZTIMER_USEC adjust params for b-l072z-lrwan1:
    CONFIG_ZTIMER_USEC_ADJUST_SET    20
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  29

make: Leaving directory '/home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead'
cbuec@W11nMate:~/RIOTstuff/riot-upstream/RIOT$
```


### Board 4
```
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2026.10-devel-278-g307c08d)
ZTIMER_USEC auto_adjust params:
    ZTIMER_USEC->adjust_set = 20
    ZTIMER_USEC->adjust_sleep = 29
ZTIMER_USEC auto_adjust params cleared
ztimer_overhead_set...
min=20 max=21 avg_diff=20
ztimer_overhead_sleep...
min=29 max=29 avg_diff=29
ZTIMER_USEC adjust params for b-l072z-lrwan1:
    CONFIG_ZTIMER_USEC_ADJUST_SET    20
    CONFIG_ZTIMER_USEC_ADJUST_SLEEP  29

make: Leaving directory '/home/cbuec/RIOTstuff/riot-upstream/RIOT/tests/sys/ztimer_overhead'
```


### Board 5
```
*** RIOT kernel panic:
HARD FAULT HANDLER

*** rebooting...

*** RIOT kernel panic:
HARD FAULT HANDLER

*** rebooting...

*** RIOT kernel panic:
HARD FAULT HANDLER

*** rebooting...
```

Seems to be broken, even the shell goes to hard fault:
```
/home/cbuec/RIOTstuff/riot-upstream/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2026-08-06_17.03.01-tests_shell-b-l072z-lrwan1"
2026-08-06 17:03:01,916 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2026-08-06 17:03:02,924 # *** RIOT kernel panic:
2026-08-06 17:03:02,924 # HARD FAULT HANDLER
2026-08-06 17:03:02,925 #
2026-08-06 17:03:02,925 # *** rebooting...
2026-08-06 17:03:02,925 #
2026-08-06 17:03:02,926 # main(): This is RIOT! (Version: 2026.10-devel-278-g307c08d)
2026-08-06 17:03:02,926 # test_shell.
> 2026-08-06 17:03:03,608 # *** RIOT kernel panic:
2026-08-06 17:03:03,611 # HARD FAULT HANDLER
2026-08-06 17:03:03,611 #
2026-08-06 17:03:03,612 # *** rebooting...
2026-08-06 17:03:03,613 #
2026-08-06 17:03:03,623 # main(): This is RIOT! (Version: 2026.10-devel-278-g307c08d)
2026-08-06 17:03:03,624 # test_shell.
```
